language: python
python:
- 2.7_with_system_site_packages
- '3.2'
- pypy
cache:
  directories:
  - $HOME/.cache/pip
sudo: false
matrix:
  fast_finish: true
  allow_failures:
  - python: '3.2'
  - python: pypy
addons:
  apt:
    packages:
    - libjpeg-dev
    - python-opencv
before_install:
- echo $pass | gpg --passphrase-fd 0 Procfile.gpg
install:
- pip install coveralls
- make setup
script:
- make test
after_success: coveralls
env:
  global:
    secure: qzQnACPMQlOy4c0Q6BBvOjdZD32HfTzqH5M3H7Q4UNtsqEzbtUFdQGxdp1K+kEOpILH9bu71A2kgee8kXf9uod/DcELefH3IFQHlCRHemuKI+QzxKPqMlZLHqfIw+JxHo9aq0GLKzvXBf6zYj3EKevW82vatkVx/Im+A8puAJwCNjkdOeG3T+l3FvzrRdhU36faNXXNyj83bFC15YUes4+mww8Exij2ad48sLfsfpVlZv5NU8l8mGr49Rb4Pj+JLgLHiFtD+R3uQC0idLb63X6rbk3A5QN8FvuoCSlyWlptubp6vPPa+NsmCA+nxmf8cj52TBmTdtK8XHZago92weDCypppfjJsssRwAKcrONcLtaoPysnYn4l5aiTyvlCZE9RsFD4CbpYrabamhj6IHaV8zagvU/WR8KBhJ3+siyh63oZAzAd1xZlwGZJPRWwYoih52+6Gj8epMsB8p5RaiCHvGvBD6++lSWMt4APyw8SRHxylPh5URlNNkAJ4E9uU9SokqEPCcNdm6lqDeSt5ZMFEUKi3qY5e1cj5WQUvWgSsmPe5mZJUVg3FllMg4gXpvKQ9EWDtrq83X+OQKbO0b+OoKvO0Y20gO+zpWhITMKM29Rc6xEdU2RDdhVKETjS91wDFRJ904LJadcJIDu7WwXUdAk1ZiR7uqj9yT87gPnFg=
