language: python
python:
- 2.7_with_system_site_packages
- '3.2'
- pypy
cache:
  directories:
  - $HOME/.cache/pip
sudo: false
matrix:
  fast_finish: true
  allow_failures:
  - python: '3.2'
  - python: pypy
addons:
  apt:
    packages:
    - libjpeg-dev
    - python-opencv
before_install:
- echo $pass | gpg --passphrase-fd 0 Procfile.gpg
install:
- pip install coveralls
- make setup
script:
- make test
after_success: coveralls
env:
  global:
    secure: QbRBtkdIfZk8GE67ztPNodY6IQOIAjA/ZIk24txjAh9BQD30Wx12IKoctYfILaj+Se0d3BnebVTAVN5CpcgX4CqXs9WhJuGgWv6xCiQXPgISVwb5VLZceIsZMkasKt/cEdfj1/RZwue381e5F4eqFHNEM8rU5uSJQf8jJITVHLASZtvmKBL2ZWb8jzLqjxeDQ9P/W6HI5mL7R0Aq9nKVN2IWrpjXoJl2JwdRbH1BS3S1j3cYS2L4Gq7XcRgf8qy/FKMVm6uXu14/VeoV/BKDriIRyifQZale7ez7+1MM6718Yt5+NI+jzM9vo4paeJiz8yEp9FmQ1cVe4px0ORRg1rjU+8DCWiSHYKH+gGRtMEOGoFGEqSW7TYB366rx7M+5NIsxnomvfHaCUIJITbuDXXidCIZsM/VRRNGgyxR3nAyM5zFx5XFyvDyMQubsPnud5BeXlkSqlSyxavV3mMisNwYBwsyZ+h0Jy10eFq/Yxy5IN4ArKtKsr9RwYel/BxLDfNs1+qNKT538VXvCrfCLwNIUgirtgZpGuzl+BWVC8a91NmN4rVR7beh4gLtXX4msoW18iBj60i7jsNpNWDKHQcGp9xLxjLsbve2R8sWwHWhRwTOm7kcKp8rsYItoKVNLXnD2jrnozL3elwaaIlgC+taSvs6qJvf3+CGk3+nqs7c=
before_deploy:
- rm ./.gitignore
deploy:
  provider: heroku
  api_key:
    secure: UxDfEnPnjbw4L8PWjnW9CIQ0IJYkC46Twajisla448MAMy5q5/juRaPVzvq/NCxoq1zg40PQMhHzj3jarMuog6JkDIcuKwsr4Oxh0ZRzcWh44sirx91ZQRdZkAxOZ4VXTM8+RRt3SqwtxGBCScVg9fH0I8m11RbZEzpFdyChJw1jYdBniI6ml+2qbWh6g+v8E6k7nfiIJAlH0zZhk4XYvxJqqFlAQW0BAzK9jUmG9ByYX53rDHnrbCWKwKbZktEyiqvlmhpOTx/v3DjC6BpJa/9ngMLZ4s1QwanhRcn1h3RUnwfJs0EMDL/JZMPzo7TO/M00Rtleu23zIQ3N9LKNUIebuQjAj971bYVLxIFthpKZvHZwUO8UoCzL003Agruv5Q2zbjf6LmSZ59lN41SziAhgYJLVG499AXlNzRDybNBsOi0d+l9NFA0yvBOCoSeFDnXLVLK455fBCac9jN6V3843zfh3nL8FEbgdY92I31KIH898+goNbQ0uJJQh7gTQ2hVA7G98oLbdnveVrqqvWXJ2hYwechQH2+nIyzXYzHsdx5C/aysZ182o0CJZtEl9LLxkaa0vt8Pzx6CXG38Q2v4aoY1tGw2J6apiMBh5W0R1RlWyPWMMDm6NcYZf1o6PzusKrpLug017s1eN89cNLfSQ5GiSvb7reH0v6B5IZ8I=
  app: fanhero-remotecv
  skip_cleanup: true
